const GET_USER_STATS = 'GET_USER_STATS';
const GET_USERS = 'GET_USERS';
const START_FETCHING = 'START_FETCHING';
const STOP_FETCHING = 'STOP_FETCHING';

export { GET_USER_STATS, GET_USERS, START_FETCHING, STOP_FETCHING };
